version: '3'
services:
  postgres:
    image: postgres:15.2
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"

  web:
    build:
      context: .
    ports:
      - "4567"
    links:
      - postgres
    environment:
      PGPASSWORD: postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "3000:3000"
volumes:
  db_data:
