development:
  adapter: postgresql
  encoding: unicode
  pool: 10
  database: sinatra_project_development
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  pool: 10
  database: sinatra_project_test
production:
  adapter: postgresql
  encoding: unicode
  pool: 10
  database: sinatra_project_production
