name: Auto Rebase on 'Ready for Release' Label

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]

jobs:
  auto-rebase:
    runs-on: ubuntu-latest

    # Only run if the PR has the label 'Ready for Release'
    if: contains(github.event.pull_request.labels.*.name, 'Ready for Release')

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOT_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "Rebase Bot"
          git config user.email "jedrek.domanski@gmail.com"

      - name: Fetch base branch
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream

      - name: Attempt rebase
        id: rebase
        run: |
          set +e
          git rebase upstream/master
          echo "Rebase exit code: $?"
          echo "rebase_status=$?" >> $GITHUB_OUTPUT
          set -e

      - name: Comment on PR if conflict occurs
        if: steps.rebase.outputs.rebase_status != '0'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "❌ Auto-rebase failed due to conflicts. Please rebase manually."
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Push rebased branch
        if: steps.rebase.outputs.rebase_status == '0'
        run: git push --force-with-lease

